---
apiVersion: v1
kind: Pod
metadata:
        name: java-1
        labels:
                env: dev
        namespace: dev
spec:
        containers:
                - name: java-01-container
                  image: vsknalli/hello-world-java:0.0.1.RELEASE
                  ports:
                   - containerPort: 5000       
